### ISSUE TITLE
Update in plantuml-stdlib, request to tag version

### ISSUE THREAD

**Issue by Potherca** [cloudogu/plantuml-cloudogu-sprites#1]
Hi! I've opened an MR in `plantuml-stdlib`to update this project there: https://github.com/plantuml/plantuml-stdlib/pull/12

It looks like [changes have been made](https://github.com/cloudogu/plantuml-cloudogu-sprites/compare/untagged-45e34af8ac65d89f6161...master) since the `*.puml` files were last updated in plantuml-stdlib, but since there is no new version was tagged, I don't know what version number to put in my MR.

Would it be possible to git tag the latest changes in master?

**Comment by schnatterer** [comment]
Hi @Potherca,

thanks for integrating!
New version is [here](https://github.com/cloudogu/plantuml-cloudogu-sprites/releases/tag/v1.0.2).

**Comment by Potherca** [comment]
Awesome, thanks!
