### ISSUE TITLE
How about adding chat service images?

### ISSUE THREAD

**Issue by netpyoung** [cloudogu/plantuml-cloudogu-sprites#5]
Actually I'm not using cloudogu's service. but I like this repo which provide various image.

But There are some missing images what I want is associate with Chat like Slack, Hangout, Skype ..

I'm not sure that kind of service is suitable on this repo but It will be make more fantastic this repo to adding that kind of images.

**Comment by schnatterer** [comment]
Thanks for reaching out.

I think there already is another library that provides those images: [tupadr3/plantuml-icon-font-sprites](https://github.com/tupadr3/plantuml-icon-font-sprites). Does that suit you?

**Comment by netpyoung** [comment]
@schnatterer Thank you. That also contains images what i want. I need to using this and that library. thx
